// <auto-generated />
namespace MvvmTools.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class User_Authors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Authors));
        
        string IMigrationMetadata.Id
        {
            get { return "201508201909114_User_Authors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
