//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace MvvmTools {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("MvvmTools.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear Image.
        /// </summary>
        internal static string ButtonClearImageText {
            get {
                return ResourceManager.GetString("ButtonClearImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose &amp;Image.
        /// </summary>
        internal static string ChooseImageButtonText {
            get {
                return ResourceManager.GetString("ChooseImageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MessageCaption {
            get {
                return ResourceManager.GetString("MessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled the OnActivate event.
        /// </summary>
        internal static string MessageOnActivateCancelled {
            get {
                return ResourceManager.GetString("MessageOnActivateCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Cancel to cancel this activation.  OK to continue.
        /// </summary>
        internal static string MessageOnActivateEntered {
            get {
                return ResourceManager.GetString("MessageOnActivateEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In OnApply.
        /// </summary>
        internal static string MessageOnApply {
            get {
                return ResourceManager.GetString("MessageOnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled the OnApply event.
        /// </summary>
        internal static string MessageOnApplyCancelled {
            get {
                return ResourceManager.GetString("MessageOnApplyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Cancel to cancel this OnApply.  OK to continue.
        /// </summary>
        internal static string MessageOnApplyEntered {
            get {
                return ResourceManager.GetString("MessageOnApplyEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnClosed.
        /// </summary>
        internal static string MessageOnClosed {
            get {
                return ResourceManager.GetString("MessageOnClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In OnDeactivate.
        /// </summary>
        internal static string MessageOnDeactivate {
            get {
                return ResourceManager.GetString("MessageOnDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled the OnDeactivate event.
        /// </summary>
        internal static string MessageOnDeactivateCancelled {
            get {
                return ResourceManager.GetString("MessageOnDeactivateCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Cancel to cancel this deactivation.  OK to continue.
        /// </summary>
        internal static string MessageOnDeactivateEntered {
            get {
                return ResourceManager.GetString("MessageOnDeactivateEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnActivate.
        /// </summary>
        internal static string OnActivate {
            get {
                return ResourceManager.GetString("OnActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnApply.
        /// </summary>
        internal static string OnApply {
            get {
                return ResourceManager.GetString("OnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnDeactivate.
        /// </summary>
        internal static string OnDeactivate {
            get {
                return ResourceManager.GetString("OnDeactivate", resourceCulture);
            }
        }
    }
}
